# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gerador_senha.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class GrafGerarSenha(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(199, 339)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 156, 279))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_tamanho_senha = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.input_tamanho_senha.setObjectName("input_tamanho_senha")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.input_tamanho_senha.addItem("")
        self.verticalLayout.addWidget(self.input_tamanho_senha)
        self.box_minuscula = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.box_minuscula.setObjectName("box_minuscula")
        self.verticalLayout.addWidget(self.box_minuscula)
        self.box_maiuscula = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.box_maiuscula.setObjectName("box_maiuscula")
        self.verticalLayout.addWidget(self.box_maiuscula)
        self.box_numeros = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.box_numeros.setObjectName("box_numeros")
        self.verticalLayout.addWidget(self.box_numeros)
        self.box_caractere_especial = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.box_caractere_especial.setObjectName("box_caractere_especial")
        self.verticalLayout.addWidget(self.box_caractere_especial)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_gerar_senha = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_gerar_senha.setObjectName("btn_gerar_senha")
        self.verticalLayout_2.addWidget(self.btn_gerar_senha)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Tamanho da Senha:"))
        self.input_tamanho_senha.setItemText(0, _translate("Form", "5"))
        self.input_tamanho_senha.setItemText(1, _translate("Form", "6"))
        self.input_tamanho_senha.setItemText(2, _translate("Form", "7"))
        self.input_tamanho_senha.setItemText(3, _translate("Form", "8"))
        self.input_tamanho_senha.setItemText(4, _translate("Form", "9"))
        self.input_tamanho_senha.setItemText(5, _translate("Form", "10"))
        self.input_tamanho_senha.setItemText(6, _translate("Form", "11"))
        self.input_tamanho_senha.setItemText(7, _translate("Form", "12"))
        self.input_tamanho_senha.setItemText(8, _translate("Form", "13"))
        self.input_tamanho_senha.setItemText(9, _translate("Form", "14"))
        self.input_tamanho_senha.setItemText(10, _translate("Form", "15"))
        self.input_tamanho_senha.setItemText(11, _translate("Form", "16"))
        self.input_tamanho_senha.setItemText(12, _translate("Form", "17"))
        self.input_tamanho_senha.setItemText(13, _translate("Form", "18"))
        self.input_tamanho_senha.setItemText(14, _translate("Form", "19"))
        self.input_tamanho_senha.setItemText(15, _translate("Form", "20"))
        self.input_tamanho_senha.setItemText(16, _translate("Form", "21"))
        self.input_tamanho_senha.setItemText(17, _translate("Form", "22"))
        self.input_tamanho_senha.setItemText(18, _translate("Form", "23"))
        self.input_tamanho_senha.setItemText(19, _translate("Form", "24"))
        self.input_tamanho_senha.setItemText(20, _translate("Form", "25"))
        self.box_minuscula.setText(_translate("Form", "incluir letras minusculas"))
        self.box_maiuscula.setText(_translate("Form", "incluir letras maiusculas"))
        self.box_numeros.setText(_translate("Form", "incluir numeros"))
        self.box_caractere_especial.setText(_translate("Form", "incluir caracteres especiais:"))
        self.label_2.setText(_translate("Form", "(!@#$%&*()-+.,;?{[}]^><:)"))
        self.btn_gerar_senha.setText(_translate("Form", "GERAR SENHA"))
        self.label_3.setText(_translate("Form", "SENHA GERADA:"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = GrafGerarSenha()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
